/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AppInstallDataRelationshipsApp;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AppInstallDataRelationships
 */
public class AppInstallDataRelationshipsTest {
    private final AppInstallDataRelationships model = new AppInstallDataRelationships();

    /**
     * Model tests for AppInstallDataRelationships
     */
    @Test
    public void testAppInstallDataRelationships() {
        // TODO: test AppInstallDataRelationships
    }

    /**
     * Test the property 'app'
     */
    @Test
    public void appTest() {
        // TODO: test app
    }

}
