/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AppsInstallSnykAppToOrgRequestRelationshipsApp;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AppsInstallSnykAppToOrgRequestRelationships
 */
public class AppsInstallSnykAppToOrgRequestRelationshipsTest {
    private final AppsInstallSnykAppToOrgRequestRelationships model = new AppsInstallSnykAppToOrgRequestRelationships();

    /**
     * Model tests for AppsInstallSnykAppToOrgRequestRelationships
     */
    @Test
    public void testAppsInstallSnykAppToOrgRequestRelationships() {
        // TODO: test AppsInstallSnykAppToOrgRequestRelationships
    }

    /**
     * Test the property 'app'
     */
    @Test
    public void appTest() {
        // TODO: test app
    }

}
