/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AppData;
import com.konfigthis.client.model.JsonApi;
import com.konfigthis.client.model.SelfLink;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AppsGetByAppIdResponse
 */
public class AppsGetByAppIdResponseTest {
    private final AppsGetByAppIdResponse model = new AppsGetByAppIdResponse();

    /**
     * Model tests for AppsGetByAppIdResponse
     */
    @Test
    public void testAppsGetByAppIdResponse() {
        // TODO: test AppsGetByAppIdResponse
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'jsonapi'
     */
    @Test
    public void jsonapiTest() {
        // TODO: test jsonapi
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
