/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BulkPackageUrlsRequestBodyDataAttributes
 */
public class BulkPackageUrlsRequestBodyDataAttributesTest {
    private final BulkPackageUrlsRequestBodyDataAttributes model = new BulkPackageUrlsRequestBodyDataAttributes();

    /**
     * Model tests for BulkPackageUrlsRequestBodyDataAttributes
     */
    @Test
    public void testBulkPackageUrlsRequestBodyDataAttributes() {
        // TODO: test BulkPackageUrlsRequestBodyDataAttributes
    }

    /**
     * Test the property 'purls'
     */
    @Test
    public void purlsTest() {
        // TODO: test purls
    }

}
