/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CollectionRelationshipsCreatedByUserData;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CollectionRelationshipsCreatedByUser
 */
public class CollectionRelationshipsCreatedByUserTest {
    private final CollectionRelationshipsCreatedByUser model = new CollectionRelationshipsCreatedByUser();

    /**
     * Model tests for CollectionRelationshipsCreatedByUser
     */
    @Test
    public void testCollectionRelationshipsCreatedByUser() {
        // TODO: test CollectionRelationshipsCreatedByUser
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
