/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CommonIssueModelVTwoAttributesProblemsInner;
import com.konfigthis.client.model.CoordinateVTwo;
import com.konfigthis.client.model.Severity;
import com.konfigthis.client.model.Slots;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CommonIssueModelVTwoAttributes
 */
public class CommonIssueModelVTwoAttributesTest {
    private final CommonIssueModelVTwoAttributes model = new CommonIssueModelVTwoAttributes();

    /**
     * Model tests for CommonIssueModelVTwoAttributes
     */
    @Test
    public void testCommonIssueModelVTwoAttributes() {
        // TODO: test CommonIssueModelVTwoAttributes
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'coordinates'
     */
    @Test
    public void coordinatesTest() {
        // TODO: test coordinates
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'effectiveSeverityLevel'
     */
    @Test
    public void effectiveSeverityLevelTest() {
        // TODO: test effectiveSeverityLevel
    }

    /**
     * Test the property 'problems'
     */
    @Test
    public void problemsTest() {
        // TODO: test problems
    }

    /**
     * Test the property 'severities'
     */
    @Test
    public void severitiesTest() {
        // TODO: test severities
    }

    /**
     * Test the property 'slots'
     */
    @Test
    public void slotsTest() {
        // TODO: test slots
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
