/*
 * Snyk API
 * Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CoordinateVTwoRemediesInnerDetails
 */
public class CoordinateVTwoRemediesInnerDetailsTest {
    private final CoordinateVTwoRemediesInnerDetails model = new CoordinateVTwoRemediesInnerDetails();

    /**
     * Model tests for CoordinateVTwoRemediesInnerDetails
     */
    @Test
    public void testCoordinateVTwoRemediesInnerDetails() {
        // TODO: test CoordinateVTwoRemediesInnerDetails
    }

    /**
     * Test the property 'upgradePackage'
     */
    @Test
    public void upgradePackageTest() {
        // TODO: test upgradePackage
    }

}
