/*
 * Snyk API
 * Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.VersioningSchema;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CustomBaseImagePatchRequestDataAttributes
 */
public class CustomBaseImagePatchRequestDataAttributesTest {
    private final CustomBaseImagePatchRequestDataAttributes model = new CustomBaseImagePatchRequestDataAttributes();

    /**
     * Model tests for CustomBaseImagePatchRequestDataAttributes
     */
    @Test
    public void testCustomBaseImagePatchRequestDataAttributes() {
        // TODO: test CustomBaseImagePatchRequestDataAttributes
    }

    /**
     * Test the property 'includeInRecommendations'
     */
    @Test
    public void includeInRecommendationsTest() {
        // TODO: test includeInRecommendations
    }

    /**
     * Test the property 'versioningSchema'
     */
    @Test
    public void versioningSchemaTest() {
        // TODO: test versioningSchema
    }

}
