/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.IssueRelationshipsIgnore;
import com.konfigthis.client.model.IssueRelationshipsOrganization;
import com.konfigthis.client.model.IssueRelationshipsScanItem;
import com.konfigthis.client.model.IssueRelationshipsTestExecutions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IssueRelationships
 */
public class IssueRelationshipsTest {
    private final IssueRelationships model = new IssueRelationships();

    /**
     * Model tests for IssueRelationships
     */
    @Test
    public void testIssueRelationships() {
        // TODO: test IssueRelationships
    }

    /**
     * Test the property 'ignore'
     */
    @Test
    public void ignoreTest() {
        // TODO: test ignore
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'scanItem'
     */
    @Test
    public void scanItemTest() {
        // TODO: test scanItem
    }

    /**
     * Test the property 'testExecutions'
     */
    @Test
    public void testExecutionsTest() {
        // TODO: test testExecutions
    }

}
