/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.InheritFromParent;
import com.konfigthis.client.model.OrgIacSettingsResponseAttributesCustomRulesParents;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrgIacSettingsResponseAttributesCustomRules
 */
public class OrgIacSettingsResponseAttributesCustomRulesTest {
    private final OrgIacSettingsResponseAttributesCustomRules model = new OrgIacSettingsResponseAttributesCustomRules();

    /**
     * Model tests for OrgIacSettingsResponseAttributesCustomRules
     */
    @Test
    public void testOrgIacSettingsResponseAttributesCustomRules() {
        // TODO: test OrgIacSettingsResponseAttributesCustomRules
    }

    /**
     * Test the property 'inheritFromParent'
     */
    @Test
    public void inheritFromParentTest() {
        // TODO: test inheritFromParent
    }

    /**
     * Test the property 'isEnabled'
     */
    @Test
    public void isEnabledTest() {
        // TODO: test isEnabled
    }

    /**
     * Test the property 'ociRegistryTag'
     */
    @Test
    public void ociRegistryTagTest() {
        // TODO: test ociRegistryTag
    }

    /**
     * Test the property 'ociRegistryUrl'
     */
    @Test
    public void ociRegistryUrlTest() {
        // TODO: test ociRegistryUrl
    }

    /**
     * Test the property 'parents'
     */
    @Test
    public void parentsTest() {
        // TODO: test parents
    }

    /**
     * Test the property 'updated'
     */
    @Test
    public void updatedTest() {
        // TODO: test updated
    }

}
