/*
 * Snyk API
 * Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SeverityThreshold;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProjectSettingsPatchRequestDataAttributes
 */
public class ProjectSettingsPatchRequestDataAttributesTest {
    private final ProjectSettingsPatchRequestDataAttributes model = new ProjectSettingsPatchRequestDataAttributes();

    /**
     * Model tests for ProjectSettingsPatchRequestDataAttributes
     */
    @Test
    public void testProjectSettingsPatchRequestDataAttributes() {
        // TODO: test ProjectSettingsPatchRequestDataAttributes
    }

    /**
     * Test the property 'isActive'
     */
    @Test
    public void isActiveTest() {
        // TODO: test isActive
    }

    /**
     * Test the property 'severityThreshold'
     */
    @Test
    public void severityThresholdTest() {
        // TODO: test severityThreshold
    }

    /**
     * Test the property 'targetChannelId'
     */
    @Test
    public void targetChannelIdTest() {
        // TODO: test targetChannelId
    }

}
