/*
 * Snyk API
 * Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AutoDependencyUpgradeSettings;
import com.konfigthis.client.model.AutoRemediationPRsSettings;
import com.konfigthis.client.model.ManualRemediationPRsSettings;
import com.konfigthis.client.model.PullRequestAssignmentSettings;
import com.konfigthis.client.model.PullRequestsSettings;
import com.konfigthis.client.model.RecurringTestsSettings;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProjectSettings
 */
public class ProjectSettingsTest {
    private final ProjectSettings model = new ProjectSettings();

    /**
     * Model tests for ProjectSettings
     */
    @Test
    public void testProjectSettings() {
        // TODO: test ProjectSettings
    }

    /**
     * Test the property 'autoDependencyUpgrade'
     */
    @Test
    public void autoDependencyUpgradeTest() {
        // TODO: test autoDependencyUpgrade
    }

    /**
     * Test the property 'autoRemediationPrs'
     */
    @Test
    public void autoRemediationPrsTest() {
        // TODO: test autoRemediationPrs
    }

    /**
     * Test the property 'manualRemediationPrs'
     */
    @Test
    public void manualRemediationPrsTest() {
        // TODO: test manualRemediationPrs
    }

    /**
     * Test the property 'pullRequestAssignment'
     */
    @Test
    public void pullRequestAssignmentTest() {
        // TODO: test pullRequestAssignment
    }

    /**
     * Test the property 'pullRequests'
     */
    @Test
    public void pullRequestsTest() {
        // TODO: test pullRequests
    }

    /**
     * Test the property 'recurringTests'
     */
    @Test
    public void recurringTestsTest() {
        // TODO: test recurringTests
    }

}
