/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinks
 */
public class ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinksTest {
    private final ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinks model = new ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinks();

    /**
     * Model tests for ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinks
     */
    @Test
    public void testProjectsListForOrgResponseDataInnerRelationshipsOwnerLinks() {
        // TODO: test ProjectsListForOrgResponseDataInnerRelationshipsOwnerLinks
    }

    /**
     * Test the property 'related'
     */
    @Test
    public void relatedTest() {
        // TODO: test related
    }

}
