/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProjectsGetByProjectIdResponseDataRelationshipsOrganizationData;
import com.konfigthis.client.model.ProjectsGetByProjectIdResponseDataRelationshipsOrganizationLinks;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProjectsGetByProjectIdResponseDataRelationshipsOrganization
 */
public class ProjectsGetByProjectIdResponseDataRelationshipsOrganizationTest {
    private final ProjectsGetByProjectIdResponseDataRelationshipsOrganization model = new ProjectsGetByProjectIdResponseDataRelationshipsOrganization();

    /**
     * Model tests for ProjectsGetByProjectIdResponseDataRelationshipsOrganization
     */
    @Test
    public void testProjectsGetByProjectIdResponseDataRelationshipsOrganization() {
        // TODO: test ProjectsGetByProjectIdResponseDataRelationshipsOrganization
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'meta'
     */
    @Test
    public void metaTest() {
        // TODO: test meta
    }

}
