/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.PublicTargetRelationshipsIntegration;
import com.konfigthis.client.model.PublicTargetRelationshipsOrganization;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PublicTargetRelationships
 */
public class PublicTargetRelationshipsTest {
    private final PublicTargetRelationships model = new PublicTargetRelationships();

    /**
     * Model tests for PublicTargetRelationships
     */
    @Test
    public void testPublicTargetRelationships() {
        // TODO: test PublicTargetRelationships
    }

    /**
     * Test the property 'integration'
     */
    @Test
    public void integrationTest() {
        // TODO: test integration
    }

    /**
     * Test the property 'organization'
     */
    @Test
    public void organizationTest() {
        // TODO: test organization
    }

}
