/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ServiceAccountsUpdateGroupNameByIdRequestDataAttributes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServiceAccountsUpdateGroupNameByIdRequestData
 */
public class ServiceAccountsUpdateGroupNameByIdRequestDataTest {
    private final ServiceAccountsUpdateGroupNameByIdRequestData model = new ServiceAccountsUpdateGroupNameByIdRequestData();

    /**
     * Model tests for ServiceAccountsUpdateGroupNameByIdRequestData
     */
    @Test
    public void testServiceAccountsUpdateGroupNameByIdRequestData() {
        // TODO: test ServiceAccountsUpdateGroupNameByIdRequestData
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
