/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServiceAccountsCreateGroupRequestDataAttributes
 */
public class ServiceAccountsCreateGroupRequestDataAttributesTest {
    private final ServiceAccountsCreateGroupRequestDataAttributes model = new ServiceAccountsCreateGroupRequestDataAttributes();

    /**
     * Model tests for ServiceAccountsCreateGroupRequestDataAttributes
     */
    @Test
    public void testServiceAccountsCreateGroupRequestDataAttributes() {
        // TODO: test ServiceAccountsCreateGroupRequestDataAttributes
    }

    /**
     * Test the property 'accessTokenTtlSeconds'
     */
    @Test
    public void accessTokenTtlSecondsTest() {
        // TODO: test accessTokenTtlSeconds
    }

    /**
     * Test the property 'authType'
     */
    @Test
    public void authTypeTest() {
        // TODO: test authType
    }

    /**
     * Test the property 'jwksUrl'
     */
    @Test
    public void jwksUrlTest() {
        // TODO: test jwksUrl
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'roleId'
     */
    @Test
    public void roleIdTest() {
        // TODO: test roleId
    }

}
