/*
 * Snyk API
 * Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SlotsReferencesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Slots
 */
public class SlotsTest {
    private final Slots model = new Slots();

    /**
     * Model tests for Slots
     */
    @Test
    public void testSlots() {
        // TODO: test Slots
    }

    /**
     * Test the property 'disclosureTime'
     */
    @Test
    public void disclosureTimeTest() {
        // TODO: test disclosureTime
    }

    /**
     * Test the property 'exploit'
     */
    @Test
    public void exploitTest() {
        // TODO: test exploit
    }

    /**
     * Test the property 'publicationTime'
     */
    @Test
    public void publicationTimeTest() {
        // TODO: test publicationTime
    }

    /**
     * Test the property 'references'
     */
    @Test
    public void referencesTest() {
        // TODO: test references
    }

}
