/*
 * Snyk API
 * Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ClassTypeDef
 */
@JsonAdapter(ClassTypeDef.Adapter.class)public enum ClassTypeDef {
  
  RULE_CATEGORY("rule-category"),
  
  COMPLIANCE("compliance"),
  
  WEAKNESS("weakness");

  private String value;

  ClassTypeDef(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ClassTypeDef fromValue(String value) {
    for (ClassTypeDef b : ClassTypeDef.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ClassTypeDef> {
    @Override
    public void write(final JsonWriter jsonWriter, final ClassTypeDef enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ClassTypeDef read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ClassTypeDef.fromValue(value);
    }
  }
}

