/*
 * Snyk API
 * Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SeverityThreshold;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ProjectSettingsDataAttributes
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ProjectSettingsDataAttributes {
  public static final String SERIALIZED_NAME_IS_ACTIVE = "is_active";
  @SerializedName(SERIALIZED_NAME_IS_ACTIVE)
  private Boolean isActive;

  public static final String SERIALIZED_NAME_SEVERITY_THRESHOLD = "severity_threshold";
  @SerializedName(SERIALIZED_NAME_SEVERITY_THRESHOLD)
  private SeverityThreshold severityThreshold;

  public static final String SERIALIZED_NAME_TARGET_CHANNEL_ID = "target_channel_id";
  @SerializedName(SERIALIZED_NAME_TARGET_CHANNEL_ID)
  private URI targetChannelId;

  public static final String SERIALIZED_NAME_TARGET_CHANNEL_NAME = "target_channel_name";
  @SerializedName(SERIALIZED_NAME_TARGET_CHANNEL_NAME)
  private String targetChannelName;

  public static final String SERIALIZED_NAME_TARGET_PROJECT_NAME = "target_project_name";
  @SerializedName(SERIALIZED_NAME_TARGET_PROJECT_NAME)
  private String targetProjectName;

  public ProjectSettingsDataAttributes() {
  }

  public ProjectSettingsDataAttributes isActive(Boolean isActive) {
    
    
    
    
    this.isActive = isActive;
    return this;
  }

   /**
   * Current status of the project settings.
   * @return isActive
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "true", required = true, value = "Current status of the project settings.")

  public Boolean getIsActive() {
    return isActive;
  }


  public void setIsActive(Boolean isActive) {
    
    
    
    this.isActive = isActive;
  }


  public ProjectSettingsDataAttributes severityThreshold(SeverityThreshold severityThreshold) {
    
    
    
    
    this.severityThreshold = severityThreshold;
    return this;
  }

   /**
   * Get severityThreshold
   * @return severityThreshold
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public SeverityThreshold getSeverityThreshold() {
    return severityThreshold;
  }


  public void setSeverityThreshold(SeverityThreshold severityThreshold) {
    
    
    
    this.severityThreshold = severityThreshold;
  }


  public ProjectSettingsDataAttributes targetChannelId(URI targetChannelId) {
    
    
    
    
    this.targetChannelId = targetChannelId;
    return this;
  }

   /**
   * Get targetChannelId
   * @return targetChannelId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "slack://channel?team=team-id&id=channel-id", required = true, value = "")

  public URI getTargetChannelId() {
    return targetChannelId;
  }


  public void setTargetChannelId(URI targetChannelId) {
    
    
    
    this.targetChannelId = targetChannelId;
  }


  public ProjectSettingsDataAttributes targetChannelName(String targetChannelName) {
    
    
    if (targetChannelName != null && targetChannelName.length() < 1) {
      throw new IllegalArgumentException("Invalid value for targetChannelName. Length must be greater than or equal to 1.");
    }
    
    this.targetChannelName = targetChannelName;
    return this;
  }

   /**
   * Get targetChannelName
   * @return targetChannelName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "channel-name", required = true, value = "")

  public String getTargetChannelName() {
    return targetChannelName;
  }


  public void setTargetChannelName(String targetChannelName) {
    
    
    if (targetChannelName != null && targetChannelName.length() < 1) {
      throw new IllegalArgumentException("Invalid value for targetChannelName. Length must be greater than or equal to 1.");
    }
    this.targetChannelName = targetChannelName;
  }


  public ProjectSettingsDataAttributes targetProjectName(String targetProjectName) {
    
    
    
    
    this.targetProjectName = targetProjectName;
    return this;
  }

   /**
   * The target file name for the project.
   * @return targetProjectName
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "snyk/goof:package.json", required = true, value = "The target file name for the project.")

  public String getTargetProjectName() {
    return targetProjectName;
  }


  public void setTargetProjectName(String targetProjectName) {
    
    
    
    this.targetProjectName = targetProjectName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ProjectSettingsDataAttributes instance itself
   */
  public ProjectSettingsDataAttributes putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProjectSettingsDataAttributes projectSettingsDataAttributes = (ProjectSettingsDataAttributes) o;
    return Objects.equals(this.isActive, projectSettingsDataAttributes.isActive) &&
        Objects.equals(this.severityThreshold, projectSettingsDataAttributes.severityThreshold) &&
        Objects.equals(this.targetChannelId, projectSettingsDataAttributes.targetChannelId) &&
        Objects.equals(this.targetChannelName, projectSettingsDataAttributes.targetChannelName) &&
        Objects.equals(this.targetProjectName, projectSettingsDataAttributes.targetProjectName)&&
        Objects.equals(this.additionalProperties, projectSettingsDataAttributes.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isActive, severityThreshold, targetChannelId, targetChannelName, targetProjectName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProjectSettingsDataAttributes {\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    severityThreshold: ").append(toIndentedString(severityThreshold)).append("\n");
    sb.append("    targetChannelId: ").append(toIndentedString(targetChannelId)).append("\n");
    sb.append("    targetChannelName: ").append(toIndentedString(targetChannelName)).append("\n");
    sb.append("    targetProjectName: ").append(toIndentedString(targetProjectName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("is_active");
    openapiFields.add("severity_threshold");
    openapiFields.add("target_channel_id");
    openapiFields.add("target_channel_name");
    openapiFields.add("target_project_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("is_active");
    openapiRequiredFields.add("severity_threshold");
    openapiRequiredFields.add("target_channel_id");
    openapiRequiredFields.add("target_channel_name");
    openapiRequiredFields.add("target_project_name");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ProjectSettingsDataAttributes
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ProjectSettingsDataAttributes.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProjectSettingsDataAttributes is not found in the empty JSON string", ProjectSettingsDataAttributes.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ProjectSettingsDataAttributes.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("target_channel_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `target_channel_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("target_channel_id").toString()));
      }
      if (!jsonObj.get("target_channel_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `target_channel_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("target_channel_name").toString()));
      }
      if (!jsonObj.get("target_project_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `target_project_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("target_project_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProjectSettingsDataAttributes.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProjectSettingsDataAttributes' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProjectSettingsDataAttributes> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProjectSettingsDataAttributes.class));

       return (TypeAdapter<T>) new TypeAdapter<ProjectSettingsDataAttributes>() {
           @Override
           public void write(JsonWriter out, ProjectSettingsDataAttributes value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ProjectSettingsDataAttributes read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ProjectSettingsDataAttributes instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProjectSettingsDataAttributes given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProjectSettingsDataAttributes
  * @throws IOException if the JSON string is invalid with respect to ProjectSettingsDataAttributes
  */
  public static ProjectSettingsDataAttributes fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProjectSettingsDataAttributes.class);
  }

 /**
  * Convert an instance of ProjectSettingsDataAttributes to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

