/*
 * Snyk API
 * Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ContainerImageGetInstanceResponse;
import com.konfigthis.client.model.ContainerImageListImageTargetRefsResponse;
import com.konfigthis.client.model.ContainerImageListInstancesOfContainerImageResponse;
import java.time.OffsetDateTime;
import com.konfigthis.client.model.Platform;
import java.net.URI;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContainerImageApi
 */
@Disabled
public class ContainerImageApiTest {

    private static ContainerImageApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ContainerImageApi(apiClient);
    }

    /**
     * Get instance of container image
     *
     * Get instance of container image
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getInstanceTest() throws ApiException {
        String version = null;
        UUID orgId = null;
        URI imageId = null;
        ContainerImageGetInstanceResponse response = api.getInstance(version, orgId, imageId)
                .execute();
        // TODO: test validations
    }

    /**
     * List instances of image target references for a container image
     *
     * List instances of image target references for a container image
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listImageTargetRefsTest() throws ApiException {
        UUID orgId = null;
        URI imageId = null;
        String version = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        ContainerImageListImageTargetRefsResponse response = api.listImageTargetRefs(orgId, imageId, version)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

    /**
     * List instances of container image
     *
     * List instances of container image
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listInstancesOfContainerImageTest() throws ApiException {
        UUID orgId = null;
        String version = null;
        List<URI> imageIds = null;
        Platform platform = null;
        List<String> names = null;
        Integer limit = null;
        String startingAfter = null;
        String endingBefore = null;
        ContainerImageListInstancesOfContainerImageResponse response = api.listInstancesOfContainerImage(orgId, version)
                .imageIds(imageIds)
                .platform(platform)
                .names(names)
                .limit(limit)
                .startingAfter(startingAfter)
                .endingBefore(endingBefore)
                .execute();
        // TODO: test validations
    }

}
