/*
 * Snyk API
 * Missing description placeholder
 *
 * The version of the OpenAPI document: REST
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import java.time.OffsetDateTime;
import com.konfigthis.client.model.SastSettingsGetForOrgResponse;
import com.konfigthis.client.model.SastSettingsToggleSnykCodeSettingsRequest;
import com.konfigthis.client.model.SastSettingsToggleSnykCodeSettingsRequestData;
import com.konfigthis.client.model.SastSettingsToggleSnykCodeSettingsResponse;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SastSettingsApi
 */
@Disabled
public class SastSettingsApiTest {

    private static SastSettingsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new SastSettingsApi(apiClient);
    }

    /**
     * Retrieves the SAST settings for an org
     *
     * Retrieves the SAST settings for an org
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getForOrgTest() throws ApiException {
        String version = null;
        UUID orgId = null;
        SastSettingsGetForOrgResponse response = api.getForOrg(version, orgId)
                .execute();
        // TODO: test validations
    }

    /**
     * Enable/Disable the Snyk Code settings for an org
     *
     * Enable/Disable the Snyk Code settings for an org
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void toggleSnykCodeSettingsTest() throws ApiException {
        SastSettingsToggleSnykCodeSettingsRequestData data = null;
        String version = null;
        UUID orgId = null;
        SastSettingsToggleSnykCodeSettingsResponse response = api.toggleSnykCodeSettings(data, version, orgId)
                .execute();
        // TODO: test validations
    }

}
